name = "FinancialPortfolios"
uuid = "7b36c455-f227-419f-b582-14f635f70924"
authors = ["Tyler Beason <tbeas12@gmail.com>"]
version = "0.1.1"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.2"
